name: ds
version: 0.0.0
description: 
author:
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  angular2: '^2.0.0-alpha.37'
  browser: '^0.10.0+2'
  test: any
transformers:
- angular2:
    entry_points: web/main.dart